import { CustomerType } from 'src/definition/customer-interfaces'

//------------------------------
//---Get All Cutomers
//------------------------------
export const GetAllCustomers = async (): Promise<CustomerType[]> => { 
    return customers
  }


  const customers: CustomerType[] = [
    {
        code: "C-101",
        firstName: "AU-name-1",
        middleName: "AU-middleName-1",
        lastName: "AU-lastName-1",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-1@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-102",
        firstName: "AU-name-2",
        middleName: "AU-middleName-2",
        lastName: "AU-lastName-2",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User2@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-103",
        firstName: "AU-name-3",
        middleName: "AU-middleName-3",
        lastName: "AU-lastName-3",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-3@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-104",
        firstName: "AU-name-4",
        middleName: "AU-middleName-4",
        lastName: "AU-lastName-4",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-4@example.com",
        kvc: "Faild",
        credit: 20000,
        description: ""
    },
    {
        code: "C-105",
        firstName: "AU-name-5",
        middleName: "AU-middleName-5",
        lastName: "AU-lastName-5",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-5@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-106",
        firstName: "IR-name-1",
        middleName: "IR-middleName-1",
        lastName: "IR-lastName-1",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-1@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-107",
        firstName: "IR-name-2",
        middleName: "IR-middleName-2",
        lastName: "IR-lastName-2",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-2@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-108",
        firstName: "IR-name-3",
        middleName: "IR-middleName-3",
        lastName: "IR-lastName-3",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-3@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-109",
        firstName: "IR-name-4",
        middleName: "IR-middleName-4",
        lastName: "IR-lastName-4",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-4@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-110",
        firstName: "IR-name-5",
        middleName: "IR-middleName-5",
        lastName: "IR-lastName-5",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-5@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-111",
        firstName: "AU-name-1",
        middleName: "AU-middleName-1",
        lastName: "AU-lastName-1",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-1@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-112",
        firstName: "AU-name-2",
        middleName: "AU-middleName-2",
        lastName: "AU-lastName-2",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User2@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-113",
        firstName: "AU-name-3",
        middleName: "AU-middleName-3",
        lastName: "AU-lastName-3",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-3@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-114",
        firstName: "AU-name-4",
        middleName: "AU-middleName-4",
        lastName: "AU-lastName-4",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-4@example.com",
        kvc: "Failed",
        credit: 20000,
        description: ""
    },
    {
        code: "C-115",
        firstName: "AU-name-5",
        middleName: "AU-middleName-5",
        lastName: "AU-lastName-5",
        country: "Australia",
        phone_code: "+61",
        phone: "412345678",
        email: "AU-User-5@example.com",
        kvc: "OK",
        credit: 20000,
        description: ""
    },
    {
        code: "C-116",
        firstName: "IR-name-1",
        middleName: "IR-middleName-1",
        lastName: "IR-lastName-1",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-1@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-117",
        firstName: "IR-name-2",
        middleName: "IR-middleName-2",
        lastName: "IR-lastName-2",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-2@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-118",
        firstName: "IR-name-3",
        middleName: "IR-middleName-3",
        lastName: "IR-lastName-3",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-3@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-119",
        firstName: "IR-name-4",
        middleName: "IR-middleName-4",
        lastName: "IR-lastName-4",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-4@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    },
    {
        code: "C-120",
        firstName: "IR-name-5",
        middleName: "IR-middleName-5",
        lastName: "IR-lastName-5",
        country: "Iran",
        phone_code: "+98",
        phone: "9123246789",
        email: "IR-User-5@example.com",
        kvc: "---",
        credit: 0,
        description: ""
    }
]
